/*
 * This source file was generated by the Gradle 'init' task
 */

package org.example;

import java.util.List;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    List<Integer> a = new MyList<>(4);
    System.out.println(a);

    for (int i = 0; i < 20; i++) {
      a.add(i/2, i);
      System.out.println(a);
    }
  }
}
